Repository 2NE1-TEAM/secondCoupang, pull requests merged in 2025-03, with the labels that each got.

#9 TimeStamp 구현
  delivery/src/main/java/com/toanyone/delivery/domain/BaseEntity.java
Labels: ✏ feat

#14 가게 초기 세팅 및 엔티티 생성
  store/.gitattributes
  store/build.gradle
  store/gradle/wrapper/gradle-wrapper.jar
  store/gradle/wrapper/gradle-wrapper.properties
  store/gradlew
  store/gradlew.bat
  store/settings.gradle
  store/src/main/java/com/toanyone/store/StoreApplication.java
  store/src/main/java/com/toanyone/store/domain/model/Address.java
  store/src/main/java/com/toanyone/store/domain/model/BaseEntity.java
  store/src/main/java/com/toanyone/store/domain/model/Location.java
  store/src/main/java/com/toanyone/store/domain/model/Store.java
  store/src/main/java/com/toanyone/store/domain/model/StoreType.java
  store/src/main/resources/application.yml
  store/src/test/java/com/toanyone/store/StoreApplicationTests.java
Labels: ✏ feat

#17 Feat/user/sign in
  .idea/.gitignore
  user/.gitattributes
  user/.gitignore
  user/Dockerfile
  user/build.gradle
  user/docker-compose.yml
  user/gradle/wrapper/gradle-wrapper.jar
  user/gradle/wrapper/gradle-wrapper.properties
  user/gradlew
  user/gradlew.bat
  user/settings.gradle
  user/src/main/java/com/toanyone/user/user/UserApplication.java
  user/src/main/java/com/toanyone/user/user/application/config/AuthConfig.java
  user/src/main/java/com/toanyone/user/user/application/service/UserService.java
  user/src/main/java/com/toanyone/user/user/domain/UserRepository.java
  user/src/main/java/com/toanyone/user/user/domain/UserRole.java
  user/src/main/java/com/toanyone/user/user/domain/dto/RequestCreateUserDto.java
  user/src/main/java/com/toanyone/user/user/domain/dto/ResponseUserDto.java
  user/src/main/java/com/toanyone/user/user/domain/entity/BaseEntity.java
  user/src/main/java/com/toanyone/user/user/domain/entity/User.java
  user/src/main/java/com/toanyone/user/user/presentation/UserController.java
  user/src/main/resources/application.yml
  user/src/test/java/com/toanyone/user/user/UserApplicationTests.java
Labels: ✏ feat, 🔧 fix

#24 init eureka-server 프로젝트 init
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/user.main.iml
  .idea/secondCoupang.iml
  .idea/vcs.xml
  eureka-server/.gitattributes
  eureka-server/.gitignore
  eureka-server/build.gradle
  eureka-server/gradle/wrapper/gradle-wrapper.jar
  eureka-server/gradle/wrapper/gradle-wrapper.properties
  eureka-server/gradlew
  eureka-server/gradlew.bat
  eureka-server/settings.gradle
  eureka-server/src/main/java/com/toanyone/eureka_server/EurekaServerApplication.java
  eureka-server/src/main/resources/application.properties
  eureka-server/src/test/java/com/toanyone/eureka_server/EurekaServerApplicationTests.java
Labels: ✏ feat

#25 init gateway init
  .idea/misc.xml
  gateway/.gitattributes
  gateway/.gitignore
  gateway/build.gradle
  gateway/gradle/wrapper/gradle-wrapper.jar
  gateway/gradle/wrapper/gradle-wrapper.properties
  gateway/gradlew
  gateway/gradlew.bat
  gateway/settings.gradle
  gateway/src/main/java/com/toanyone/gateway/GatewayApplication.java
  gateway/src/main/resources/application.properties
  gateway/src/test/java/com/toanyone/gateway/GatewayApplicationTests.java
Labels: ✏ feat

#29 Feat/user/login
  eureka-server/src/main/java/com/toanyone/eureka_server/EurekaServerApplication.java
  eureka-server/src/main/resources/application.properties
  eureka-server/src/main/resources/application.yml
  gateway/src/main/resources/application.properties
  gateway/src/main/resources/application.yml
  user/build.gradle
  user/src/main/java/com/toanyone/user/user/application/service/UserService.java
  user/src/main/java/com/toanyone/user/user/domain/dto/RequestLoginUserDto.java
  user/src/main/java/com/toanyone/user/user/infrastructure/JwtUtil.java
  user/src/main/java/com/toanyone/user/user/presentation/UserController.java
  user/src/main/resources/application.yml
Labels: ✏ feat

#11 주문 프로젝트 세팅
  order/.gitattributes
  order/.gitignore
  order/build.gradle
  order/gradle/wrapper/gradle-wrapper.properties
  order/gradlew
  order/gradlew.bat
  order/settings.gradle
  order/src/main/java/com/toanyone/order/OrderApplication.java
  order/src/main/java/com/toanyone/order/common/BaseEntity.java
  order/src/main/java/com/toanyone/order/domain/entity/Order.java
  order/src/main/java/com/toanyone/order/domain/entity/OrderItem.java
  order/src/main/resources/application-prod.yml
  order/src/main/resources/application.yml
  order/src/test/java/com/toanyone/order/OrderApplicationTests.java
Labels: ✏ feat

#28 DeliveryRoad, DeliveryManager 엔티티 생성
  delivery/src/main/java/com/toanyone/delivery/domain/DeliveryManager.java
  delivery/src/main/java/com/toanyone/delivery/domain/DeliveryRoad.java
Labels: ✏ feat

#30 스토어 주문, 삭제, 단건조회 로직 구현 및 전화번호 검증 utils 구현
  store/build.gradle
  store/src/main/java/com/toanyone/store/StoreApplication.java
  store/src/main/java/com/toanyone/store/application/service/StoreServiceImpl.java
  store/src/main/java/com/toanyone/store/common/util/PhoneNumberUtils.java
  store/src/main/java/com/toanyone/store/domain/exception/CustomException.java
  store/src/main/java/com/toanyone/store/domain/exception/StoreException.java
  store/src/main/java/com/toanyone/store/domain/model/BaseEntity.java
  store/src/main/java/com/toanyone/store/domain/model/DetailAddress.java
  store/src/main/java/com/toanyone/store/domain/model/Store.java
  store/src/main/java/com/toanyone/store/domain/model/StoreType.java
  store/src/main/java/com/toanyone/store/domain/repository/StoreRepository.java
  store/src/main/java/com/toanyone/store/domain/service/StoreService.java
  store/src/main/java/com/toanyone/store/infrastructure/client/HubClient.java
  store/src/main/java/com/toanyone/store/infrastructure/client/dto/HubResponseDto.java
  store/src/main/java/com/toanyone/store/infrastructure/repository/JpaStoreRepository.java
  store/src/main/java/com/toanyone/store/infrastructure/repository/StoreRepositoryCustom.java
  store/src/main/java/com/toanyone/store/infrastructure/repository/StoreRepositoryImpl.java
  store/src/main/java/com/toanyone/store/presentation/controller/StoreController.java
  store/src/main/java/com/toanyone/store/presentation/dto/MultiResponse.java
  store/src/main/java/com/toanyone/store/presentation/dto/SingleResponse.java
  store/src/main/java/com/toanyone/store/presentation/dto/StoreCreateRequestDto.java
  store/src/main/java/com/toanyone/store/presentation/dto/StoreCreateResponseDto.java
  store/src/main/java/com/toanyone/store/presentation/dto/StoreFindResponseDto.java
  store/src/test/java/com/toanyone/store/application/service/StoreServiceImplTest.java
  store/src/test/java/com/toanyone/store/common/util/PhoneNumberUtilsTest.java
Labels: ✏ feat

#32 배송 담당 매니저 생성 기능 구현
  delivery/src/main/java/com/toanyone/delivery/application/DeliveryService.java
  delivery/src/main/java/com/toanyone/delivery/application/dtos/request/CreateDeliveryManagerRequestDto.java
  delivery/src/main/java/com/toanyone/delivery/application/dtos/response/CreateDeliveryManagerResponseDto.java
  delivery/src/main/java/com/toanyone/delivery/application/exception/DeliveryManagerException.java
  delivery/src/main/java/com/toanyone/delivery/common/CustomException.java
  delivery/src/main/java/com/toanyone/delivery/common/MultiResponse.java
  delivery/src/main/java/com/toanyone/delivery/common/SingleResponse.java
  delivery/src/main/java/com/toanyone/delivery/domain/DeliveryManager.java
  delivery/src/main/java/com/toanyone/delivery/domain/repository/DeliveryManagerRepository.java
  delivery/src/main/java/com/toanyone/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/toanyone/delivery/infrastructure/DeliveryManagerRepositoryImpl.java
  delivery/src/main/java/com/toanyone/delivery/infrastructure/DeliveryRepositoryImpl.java
  delivery/src/main/java/com/toanyone/delivery/presentation/DeliveryController.java
  delivery/src/test/java/com/toanyone/delivery/application/DeliveryServiceTest.java
Labels: ✏ feat, 📋 test

#31 주문 생성 관련 Item 검증 및 주문 생성 구현
  order/.gitignore
  order/build.gradle
  order/src/main/java/com/toanyone/order/application/ItemService.java
  order/src/main/java/com/toanyone/order/application/ItemServiceImplTemp.java
  order/src/main/java/com/toanyone/order/application/OrderService.java
  order/src/main/java/com/toanyone/order/application/dto/ItemValidationRequestDto.java
  order/src/main/java/com/toanyone/order/application/dto/ItemValidationResponseDto.java
  order/src/main/java/com/toanyone/order/common/MultiResponse.java
  order/src/main/java/com/toanyone/order/common/SingleResponse.java
  order/src/main/java/com/toanyone/order/common/exception/CustomException.java
  order/src/main/java/com/toanyone/order/common/exception/GlobalExceptionHandler.java
  order/src/main/java/com/toanyone/order/common/exception/OrderException.java
  order/src/main/java/com/toanyone/order/domain/entity/Order.java
  order/src/main/java/com/toanyone/order/domain/entity/OrderItem.java
  order/src/main/java/com/toanyone/order/domain/repository/OrderRepository.java
  order/src/main/java/com/toanyone/order/infrastructure/JpaOrderRepository.java
  order/src/main/java/com/toanyone/order/infrastructure/client/ItemClient.java
  order/src/main/java/com/toanyone/order/presentation/OrderController.java
  order/src/main/java/com/toanyone/order/presentation/dto/request/OrderCreateRequestDto.java
  order/src/main/java/com/toanyone/order/presentation/dto/response/OrderCreateResponseDto.java
  order/src/test/java/com/toanyone/order/application/OrderServiceTest.java
Labels: ✏ feat, 📋 test

#36 배송담당자 조회 기능 구현
  delivery/build.gradle
  delivery/src/main/java/com/toanyone/delivery/application/DeliveryService.java
  delivery/src/main/java/com/toanyone/delivery/application/dtos/request/GetDeliveryManagerSearchConditionRequestDto.java
  delivery/src/main/java/com/toanyone/delivery/application/dtos/response/GetDeliveryManagerResponseDto.java
  delivery/src/main/java/com/toanyone/delivery/application/exception/DeliveryManagerException.java
  delivery/src/main/java/com/toanyone/delivery/common/MultiResponse.java
  delivery/src/main/java/com/toanyone/delivery/common/config/QueryDslConfig.java
  delivery/src/main/java/com/toanyone/delivery/common/exception/CustomException.java
  delivery/src/main/java/com/toanyone/delivery/common/utils/MultiResponse.java
  delivery/src/main/java/com/toanyone/delivery/common/utils/SingleResponse.java
  delivery/src/main/java/com/toanyone/delivery/domain/repository/CustomDeliveryMangerRepository.java
  delivery/src/main/java/com/toanyone/delivery/infrastructure/CustomDeliverManagerRepositoryImpl.java
  delivery/src/main/java/com/toanyone/delivery/presentation/DeliveryController.java
  delivery/src/test/java/com/toanyone/delivery/application/DeliveryServiceTest.java
Labels: ✏ feat, 📋 test

#46 스토어 CRUD 구현
  store/build.gradle
  store/src/main/generated/com/toanyone/store/domain/model/QBaseEntity.java
  store/src/main/generated/com/toanyone/store/domain/model/QDetailAddress.java
  store/src/main/generated/com/toanyone/store/domain/model/QStore.java
  store/src/main/java/com/toanyone/store/application/service/StoreServiceImpl.java
  store/src/main/java/com/toanyone/store/common/config/AuditorConfig/getCurrentAuditor.java
  store/src/main/java/com/toanyone/store/common/config/querydslConfig/QueryDslConfig.java
  store/src/main/java/com/toanyone/store/common/exception/StoreExceptionHandler.java
  store/src/main/java/com/toanyone/store/common/filter/UserContext.java
  store/src/main/java/com/toanyone/store/common/filter/UserInfoFilter.java
  store/src/main/java/com/toanyone/store/domain/model/BaseEntity.java
  store/src/main/java/com/toanyone/store/domain/model/Store.java
  store/src/main/java/com/toanyone/store/domain/repository/StoreRepository.java
  store/src/main/java/com/toanyone/store/domain/service/StoreService.java
  store/src/main/java/com/toanyone/store/infrastructure/client/HubClient.java
  store/src/main/java/com/toanyone/store/infrastructure/client/dto/HubResponseDto.java
  store/src/main/java/com/toanyone/store/infrastructure/repository/JpaStoreRepository.java
  store/src/main/java/com/toanyone/store/infrastructure/repository/StoreRepositoryCustom.java
  store/src/main/java/com/toanyone/store/infrastructure/repository/StoreRepositoryImpl.java
  store/src/main/java/com/toanyone/store/presentation/controller/StoreController.java
  store/src/main/java/com/toanyone/store/presentation/dto/CursorInfo.java
  store/src/main/java/com/toanyone/store/presentation/dto/CursorPage.java
  store/src/main/java/com/toanyone/store/presentation/dto/MultiResponse.java
  store/src/main/java/com/toanyone/store/presentation/dto/StoreSearchRequest.java
  store/src/main/java/com/toanyone/store/presentation/dto/StoreUpdateRequestDto.java
  store/src/main/java/com/toanyone/store/presentation/dto/UserInfo.java
  store/src/test/java/com/toanyone/store/StoreApplicationTests.java
  store/src/test/java/com/toanyone/store/application/service/StoreServiceImplTest.java
  store/src/test/java/com/toanyone/store/common/util/PhoneNumberUtilsTest.java
Labels: ✏ feat, 📋 test

#65 Feat/ai/create
  ai/.gitattributes
  ai/.gitignore
  ai/build.gradle
  ai/gradle/wrapper/gradle-wrapper.jar
  ai/gradle/wrapper/gradle-wrapper.properties
  ai/gradlew
  ai/gradlew.bat
  ai/settings.gradle
  ai/src/main/java/com/toanyone/ai/AiApplication.java
  ai/src/main/java/com/toanyone/ai/application/config/WebClientConfig.java
  ai/src/main/java/com/toanyone/ai/application/service/AiService.java
  ai/src/main/java/com/toanyone/ai/application/service/SlackService.java
  ai/src/main/java/com/toanyone/ai/application/service/TotalService.java
  ai/src/main/java/com/toanyone/ai/common/BaseEntity.java
  ai/src/main/java/com/toanyone/ai/common/exception/AIException.java
  ai/src/main/java/com/toanyone/ai/common/exception/CustomException.java
  ai/src/main/java/com/toanyone/ai/common/exception/GlobalExceptionHandler.java
  ai/src/main/java/com/toanyone/ai/common/response/MultiResponse.java
  ai/src/main/java/com/toanyone/ai/common/response/SingleResponse.java
  ai/src/main/java/com/toanyone/ai/domain/entity/Ai.java
  ai/src/main/java/com/toanyone/ai/domain/entity/OrderStatus.java
  ai/src/main/java/com/toanyone/ai/domain/entity/SlackMessage.java
  ai/src/main/java/com/toanyone/ai/infrastructure/AiRepository.java
  ai/src/main/java/com/toanyone/ai/infrastructure/SlackRepository.java
  ai/src/main/java/com/toanyone/ai/presentation/controller/SlackController.java
  ai/src/main/java/com/toanyone/ai/presentation/controller/TotalController.java
  ai/src/main/java/com/toanyone/ai/presentation/dto/RequestCreateMessageDto.java
  ai/src/main/java/com/toanyone/ai/presentation/dto/RequestGeminiDto.java
  ai/src/main/java/com/toanyone/ai/presentation/dto/ResponseGeminiDto.java
  ai/src/main/java/com/toanyone/ai/presentation/dto/ResponseGetSlackDto.java
  ai/src/main/resources/application.yml
  ai/src/test/java/com/toanyone/ai/AiApplicationTests.java
  gateway/src/main/resources/application.yml
Labels: ✏ feat

#67 허브 CRUD, 엔티티 생성, redids 캐싱, 카프카 설정
  hub/.gitattributes
  hub/build.gradle
  hub/gradle/wrapper/gradle-wrapper.jar
  hub/gradle/wrapper/gradle-wrapper.properties
  hub/gradlew
  hub/gradlew.bat
  hub/settings.gradle
  hub/src/main/java/com/toanyone/hub/HubApplication.java
  hub/src/main/java/com/toanyone/hub/application/dto/TestDto.java
  hub/src/main/java/com/toanyone/hub/application/service/HubServiceImpl.java
  hub/src/main/java/com/toanyone/hub/application/service/KakaoDirectionService.java
  hub/src/main/java/com/toanyone/hub/application/service/RouteServiceImpl.java
  hub/src/main/java/com/toanyone/hub/common/config/AuditorConfig/getCurrentAuditor.java
  hub/src/main/java/com/toanyone/hub/common/config/kafkaConfig/KafkaConsumerConfig.java
  hub/src/main/java/com/toanyone/hub/common/config/kafkaConfig/KafkaProducerConfig.java
  hub/src/main/java/com/toanyone/hub/common/config/querydslConfig/QueryDslConfig.java
  hub/src/main/java/com/toanyone/hub/common/config/redisConfig/RedisConfig.java
  hub/src/main/java/com/toanyone/hub/common/config/restTemplate/RestTemplateConfig.java
  hub/src/main/java/com/toanyone/hub/common/exception/HubExceptionHandler.java
  hub/src/main/java/com/toanyone/hub/common/filter/UserContext.java
  hub/src/main/java/com/toanyone/hub/common/filter/UserInfoFilter.java
  hub/src/main/java/com/toanyone/hub/common/util/PhoneNumberUtils.java
  hub/src/main/java/com/toanyone/hub/domain/exception/CustomException.java
  hub/src/main/java/com/toanyone/hub/domain/exception/HubException.java
  hub/src/main/java/com/toanyone/hub/domain/model/Address.java
  hub/src/main/java/com/toanyone/hub/domain/model/BaseEntity.java
  hub/src/main/java/com/toanyone/hub/domain/model/Hub.java
  hub/src/main/java/com/toanyone/hub/domain/model/HubDistance.java
  hub/src/main/java/com/toanyone/hub/domain/model/Location.java
  hub/src/main/java/com/toanyone/hub/domain/repository/HubDistanceRepository.java
  hub/src/main/java/com/toanyone/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/toanyone/hub/domain/service/HubService.java
  hub/src/main/java/com/toanyone/hub/domain/service/RouteService.java
  hub/src/main/java/com/toanyone/hub/infrastructure/init/HubDataInitializer.java
  hub/src/main/java/com/toanyone/hub/infrastructure/init/HubDistanceSqlExporter.java
  hub/src/main/java/com/toanyone/hub/infrastructure/messaging/KafkaConsumerService.java
  hub/src/main/java/com/toanyone/hub/infrastructure/messaging/KafkaProducerService.java
  hub/src/main/java/com/toanyone/hub/infrastructure/repository/HubRepositoryCustom.java
  hub/src/main/java/com/toanyone/hub/infrastructure/repository/HubRepositoryImpl.java
  hub/src/main/java/com/toanyone/hub/presentation/controller/HubController.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/CursorInfo.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/CursorPage.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/HubCreateRequestDto.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/HubCreateResponseDto.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/HubDto.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/HubFindResponseDto.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/HubSearchRequest.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/HubUpdateRequestDto.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/LocationDto.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/MultiResponse.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/RouteDTO.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/RouteSegmentDto.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/SingleResponse.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/UserInfo.java
  hub/src/main/resources/application.yml
  hub/src/main/resources/import.sql
  hub/src/test/java/com/toanyone/hub/application/service/HubServiceImplTest.java
  hub/src/test/java/com/toanyone/hub/application/service/RouteServiceImplTest.java
Labels: ✏ feat

#80 user 조회 기능 추가, slack 메세지 api 추가, (created, updated, deleted)경우의 id 대입로직 추가
  ai/build.gradle
  ai/src/main/java/com/toanyone/ai/application/service/AiService.java
  ai/src/main/java/com/toanyone/ai/application/service/SlackService.java
  ai/src/main/java/com/toanyone/ai/application/service/TotalService.java
  ai/src/main/java/com/toanyone/ai/common/BaseEntity.java
  ai/src/main/java/com/toanyone/ai/infrastructure/SlackRepository.java
  ai/src/main/java/com/toanyone/ai/presentation/controller/SlackController.java
  ai/src/main/java/com/toanyone/ai/presentation/controller/TotalController.java
  ai/src/main/java/com/toanyone/ai/presentation/dto/RequestCreateSlackDto.java
  ai/src/main/java/com/toanyone/ai/presentation/dto/ResponseCreateSlackDto.java
  ai/src/main/resources/application.yml
  gateway/build.gradle
  gateway/src/main/resources/application.yml
  user/build.gradle
  user/src/main/java/com/toanyone/user/user/application/service/UserService.java
  user/src/main/java/com/toanyone/user/user/common/BaseEntity.java
  user/src/main/java/com/toanyone/user/user/domain/UserRepository.java
  user/src/main/java/com/toanyone/user/user/domain/entity/User.java
  user/src/main/java/com/toanyone/user/user/presentation/UserController.java
  user/src/main/java/com/toanyone/user/user/presentation/dto/ResponseGetUserDto.java
  user/src/main/resources/application.yml
Labels: ✏ feat, 🔧 fix

#78 주문 리팩토링
  order/src/main/java/com/toanyone/order/application/HubService.java
  order/src/main/java/com/toanyone/order/application/ItemService.java
  order/src/main/java/com/toanyone/order/application/StoreService.java
  order/src/main/java/com/toanyone/order/application/dto/ItemValidationRequestDto.java
  order/src/main/java/com/toanyone/order/application/dto/SlackMessageRequestDto.java
  order/src/main/java/com/toanyone/order/application/dto/request/OrderFindAllCondition.java
  order/src/main/java/com/toanyone/order/application/dto/request/OrderSearchCondition.java
  order/src/main/java/com/toanyone/order/application/mapper/ItemRequestMapper.java
  order/src/main/java/com/toanyone/order/application/service/AiService.java
  order/src/main/java/com/toanyone/order/application/service/HubService.java
  order/src/main/java/com/toanyone/order/application/service/ItemService.java
  order/src/main/java/com/toanyone/order/application/service/OrderKafkaConsumer.java
  order/src/main/java/com/toanyone/order/application/service/OrderKafkaProducer.java
  order/src/main/java/com/toanyone/order/application/service/OrderService.java
  order/src/main/java/com/toanyone/order/application/service/StoreService.java
  order/src/main/java/com/toanyone/order/common/config/FeignConfig.java
  order/src/main/java/com/toanyone/order/common/config/UserAuditorAware.java
  order/src/main/java/com/toanyone/order/common/config/UserContext.java
  order/src/main/java/com/toanyone/order/common/dto/CursorConstants.java
  order/src/main/java/com/toanyone/order/common/dto/CursorInfo.java
  order/src/main/java/com/toanyone/order/common/dto/CursorPage.java
  order/src/main/java/com/toanyone/order/common/dto/MultiResponse.java
  order/src/main/java/com/toanyone/order/common/dto/SingleResponse.java
  order/src/main/java/com/toanyone/order/common/dto/SortType.java
  order/src/main/java/com/toanyone/order/common/exception/GlobalExceptionHandler.java
  order/src/main/java/com/toanyone/order/common/filter/CustomFilter.java
  order/src/main/java/com/toanyone/order/common/interceptor/CustomHeaderInterceptor.java
  order/src/main/java/com/toanyone/order/common/model/BaseEntity.java
  order/src/main/java/com/toanyone/order/domain/model/Order.java
  order/src/main/java/com/toanyone/order/domain/model/OrderItem.java
  order/src/main/java/com/toanyone/order/domain/repository/OrderItemRepository.java
  order/src/main/java/com/toanyone/order/domain/repository/OrderRepository.java
  order/src/main/java/com/toanyone/order/infrastructure/OrderQueryDslRepository.java
  order/src/main/java/com/toanyone/order/infrastructure/client/AiClient.java
  order/src/main/java/com/toanyone/order/infrastructure/client/HubClient.java
  order/src/main/java/com/toanyone/order/infrastructure/client/ItemClient.java
  order/src/main/java/com/toanyone/order/infrastructure/client/StoreClient.java
  order/src/main/java/com/toanyone/order/infrastructure/repository/JpaOrderItemRepository.java
  order/src/main/java/com/toanyone/order/infrastructure/repository/JpaOrderRepository.java
  order/src/main/java/com/toanyone/order/infrastructure/repository/OrderQueryDslRepository.java
  order/src/main/java/com/toanyone/order/infrastructure/repository/OrderQueryDslRepositoryImpl.java
  order/src/main/java/com/toanyone/order/presentation/controller/OrderController.java
  order/src/main/java/com/toanyone/order/presentation/dto/request/OrderFindAllRequestDto.java
  order/src/main/java/com/toanyone/order/presentation/dto/request/OrderSearchRequestDto.java
  order/src/main/java/com/toanyone/order/presentation/dto/response/OrderCancelResponseDto.java
  order/src/main/java/com/toanyone/order/presentation/dto/response/OrderCreateResponseDto.java
  order/src/main/java/com/toanyone/order/presentation/dto/response/OrderFindAllResponseDto.java
  order/src/main/java/com/toanyone/order/presentation/dto/response/OrderFindResponseDto.java
  order/src/main/java/com/toanyone/order/presentation/dto/response/OrderSearchResponseDto.java
  order/src/main/resources/application-prod.yml
  order/src/main/resources/application.yml
  order/src/test/java/com/toanyone/order/application/OrderServiceTest.java
Labels: 🔧 fix, 🛠 refactor

#76 허브 FeignClient, 비동기 처리 슬랙Id추가 업데이트 로직 추가
  hub/build.gradle
  hub/src/main/java/com/toanyone/hub/HubApplication.java
  hub/src/main/java/com/toanyone/hub/application/dto/TestDto.java
  hub/src/main/java/com/toanyone/hub/application/service/HubServiceImpl.java
  hub/src/main/java/com/toanyone/hub/application/service/KakaoDirectionService.java
  hub/src/main/java/com/toanyone/hub/application/service/RouteServiceImpl.java
  hub/src/main/java/com/toanyone/hub/common/config/AuditorConfig/getCurrentAuditor.java
  hub/src/main/java/com/toanyone/hub/common/config/annotation/RequireRole.java
  hub/src/main/java/com/toanyone/hub/common/config/annotation/RoleCheckAspect.java
  hub/src/main/java/com/toanyone/hub/common/config/feignConfig/FeignConfig.java
  hub/src/main/java/com/toanyone/hub/common/config/interceptor/UserInfoHeaderInterceptor.java
  hub/src/main/java/com/toanyone/hub/common/config/kafkaConfig/KafkaConsumerConfig.java
  hub/src/main/java/com/toanyone/hub/common/exception/HubExceptionHandler.java
  hub/src/main/java/com/toanyone/hub/common/filter/UserContext.java
  hub/src/main/java/com/toanyone/hub/common/filter/UserInfoFilter.java
  hub/src/main/java/com/toanyone/hub/domain/exception/HubException.java
  hub/src/main/java/com/toanyone/hub/domain/model/BaseEntity.java
  hub/src/main/java/com/toanyone/hub/domain/model/Hub.java
  hub/src/main/java/com/toanyone/hub/domain/model/HubDistance.java
  hub/src/main/java/com/toanyone/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/toanyone/hub/domain/service/HubService.java
  hub/src/main/java/com/toanyone/hub/domain/service/RouteService.java
  hub/src/main/java/com/toanyone/hub/infrastructure/client/SlackClient.java
  hub/src/main/java/com/toanyone/hub/infrastructure/client/dto/RequestCreateMessageDto.java
  hub/src/main/java/com/toanyone/hub/infrastructure/configuration/SlackClientErrorDecoder.java
  hub/src/main/java/com/toanyone/hub/infrastructure/init/HubDataInitializer.java
  hub/src/main/java/com/toanyone/hub/infrastructure/messaging/HubCreateEventHandler.java
  hub/src/main/java/com/toanyone/hub/infrastructure/messaging/KafkaConsumerService.java
  hub/src/main/java/com/toanyone/hub/infrastructure/messaging/KafkaProducerService.java
  hub/src/main/java/com/toanyone/hub/infrastructure/messaging/dto/HubCreateMessage.java
  hub/src/main/java/com/toanyone/hub/infrastructure/repository/HubRepositoryImpl.java
  hub/src/main/java/com/toanyone/hub/presentation/controller/HubController.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/HubFindResponseDto.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/HubUpdateRequestDto.java
  hub/src/main/java/com/toanyone/hub/presentation/dto/HubUpdateResponseDto.java
  hub/src/main/resources/application.yml
  hub/src/test/java/com/toanyone/hub/application/service/HubServiceImplTest.java
Labels: ✏ feat, 🔧 fix

#75 스토어 레디스, 업데이트, 권한체크
  store/build.gradle
  store/src/main/generated/com/toanyone/store/domain/model/QLocation.java
  store/src/main/java/com/toanyone/store/application/service/StoreServiceImpl.java
  store/src/main/java/com/toanyone/store/common/config/AuditorConfig/getCurrentAuditor.java
  store/src/main/java/com/toanyone/store/common/config/annotation/RequireRole.java
  store/src/main/java/com/toanyone/store/common/config/annotation/RoleCheckAspect.java
  store/src/main/java/com/toanyone/store/common/config/feignConfig/FeignConfig.java
  store/src/main/java/com/toanyone/store/common/config/interceptor/UserInfoHeaderInterceptor.java
  store/src/main/java/com/toanyone/store/common/config/kafkaConfig/KafkaConfig.java
  store/src/main/java/com/toanyone/store/common/config/redisConfig/RedisConfig.java
  store/src/main/java/com/toanyone/store/common/exception/StoreExceptionHandler.java
  store/src/main/java/com/toanyone/store/common/filter/UserContext.java
  store/src/main/java/com/toanyone/store/common/filter/UserInfoFilter.java
  store/src/main/java/com/toanyone/store/domain/exception/CustomException.java
  store/src/main/java/com/toanyone/store/domain/exception/StoreException.java
  store/src/main/java/com/toanyone/store/domain/model/BaseEntity.java
  store/src/main/java/com/toanyone/store/domain/model/DetailAddress.java
  store/src/main/java/com/toanyone/store/domain/model/Location.java
  store/src/main/java/com/toanyone/store/domain/model/Store.java
  store/src/main/java/com/toanyone/store/domain/model/StoreType.java
  store/src/main/java/com/toanyone/store/domain/repository/StoreRepository.java
  store/src/main/java/com/toanyone/store/domain/service/StoreService.java
  store/src/main/java/com/toanyone/store/infrastructure/client/HubClient.java
  store/src/main/java/com/toanyone/store/infrastructure/client/dto/HubResponseDto.java
  store/src/main/java/com/toanyone/store/infrastructure/configuration/HubClientErrorDecoder.java
  store/src/main/java/com/toanyone/store/infrastructure/init/StoreDataInitializer.java
  store/src/main/java/com/toanyone/store/infrastructure/repository/StoreRepositoryCustom.java
  store/src/main/java/com/toanyone/store/infrastructure/repository/StoreRepositoryImpl.java
  store/src/main/java/com/toanyone/store/presentation/controller/StoreController.java
  store/src/main/java/com/toanyone/store/presentation/dto/CursorInfo.java
  store/src/main/java/com/toanyone/store/presentation/dto/CursorPage.java
  store/src/main/java/com/toanyone/store/presentation/dto/StoreCreateRequestDto.java
  store/src/main/java/com/toanyone/store/presentation/dto/StoreFindResponseDto.java
  store/src/main/java/com/toanyone/store/presentation/dto/StoreSearchRequest.java
  store/src/main/java/com/toanyone/store/presentation/dto/StoreUpdateRequestDto.java
  store/src/main/java/com/toanyone/store/presentation/dto/StoreUpdateResponseDto.java
  store/src/main/resources/application.yml
  store/src/test/java/com/toanyone/store/application/service/StoreServiceImplTest.java
Labels: ✏ feat, 🔧 fix

#81 아이템 레디스 설정 및 재고 증가, 감소 로직 추가
  item/.gitattributes
  item/build.gradle
  item/gradle/wrapper/gradle-wrapper.jar
  item/gradle/wrapper/gradle-wrapper.properties
  item/gradlew
  item/gradlew.bat
  item/settings.gradle
  item/src/main/java/com/toanyone/item/ItemApplication.java
  item/src/main/java/com/toanyone/item/application/service/ItemServiceImpl.java
  item/src/main/java/com/toanyone/item/common/config/AuditorConfig/getCurrentAuditor.java
  item/src/main/java/com/toanyone/item/common/config/annotation/RequireRole.java
  item/src/main/java/com/toanyone/item/common/config/annotation/RoleCheckAspect.java
  item/src/main/java/com/toanyone/item/common/config/feignConfig/FeignConfig.java
  item/src/main/java/com/toanyone/item/common/config/interceptor/UserInfoHeaderInterceptor.java
  item/src/main/java/com/toanyone/item/common/config/kafkaConfig/KafkaConsumerConfig.java
  item/src/main/java/com/toanyone/item/common/config/kafkaConfig/KafkaProducerConfig.java
  item/src/main/java/com/toanyone/item/common/config/querydslConfig/QueryDslConfig.java
  item/src/main/java/com/toanyone/item/common/config/redisConfig/RedisConfig.java
  item/src/main/java/com/toanyone/item/common/exception/StoreExceptionHandler.java
  item/src/main/java/com/toanyone/item/common/filter/UserContext.java
  item/src/main/java/com/toanyone/item/common/filter/UserInfoFilter.java
  item/src/main/java/com/toanyone/item/common/util/PhoneNumberUtils.java
  item/src/main/java/com/toanyone/item/domain/exception/CustomException.java
  item/src/main/java/com/toanyone/item/domain/exception/ItemException.java
  item/src/main/java/com/toanyone/item/domain/model/BaseEntity.java
  item/src/main/java/com/toanyone/item/domain/model/Item.java
  item/src/main/java/com/toanyone/item/domain/repository/ItemRepository.java
  item/src/main/java/com/toanyone/item/domain/service/ItemService.java
  item/src/main/java/com/toanyone/item/infrastructure/client/StoreClient.java
  item/src/main/java/com/toanyone/item/infrastructure/configuration/StoreClientErrorDecoder.java
  item/src/main/java/com/toanyone/item/infrastructure/init/StoreDataInitializer.java
  item/src/main/java/com/toanyone/item/infrastructure/repository/ItemRepositoryCustom.java
  item/src/main/java/com/toanyone/item/infrastructure/repository/ItemRepositoryImpl.java
  item/src/main/java/com/toanyone/item/presentation/controller/ItemController.java
  item/src/main/java/com/toanyone/item/presentation/dto/AdjustmentType.java
  item/src/main/java/com/toanyone/item/presentation/dto/CursorInfo.java
  item/src/main/java/com/toanyone/item/presentation/dto/CursorPage.java
  item/src/main/java/com/toanyone/item/presentation/dto/ItemCreateRequestDto.java
  item/src/main/java/com/toanyone/item/presentation/dto/ItemCreateResponseDto.java
  item/src/main/java/com/toanyone/item/presentation/dto/ItemFindResponseDto.java
  item/src/main/java/com/toanyone/item/presentation/dto/ItemSearchRequest.java
  item/src/main/java/com/toanyone/item/presentation/dto/ItemStockRequestDto.java
  item/src/main/java/com/toanyone/item/presentation/dto/ItemStockResponseDto.java
  item/src/main/java/com/toanyone/item/presentation/dto/ItemUpdateRequestDto.java
  item/src/main/java/com/toanyone/item/presentation/dto/ItemUpdateResponseDto.java
  item/src/main/java/com/toanyone/item/presentation/dto/MultiResponse.java
  item/src/main/java/com/toanyone/item/presentation/dto/SingleResponse.java
  item/src/main/java/com/toanyone/item/presentation/dto/UserInfo.java
  item/src/main/resources/application.yml
Labels: ✏ feat

#88 FeignClient에서 UserContext 사용하는 부분 수정
  hub/src/main/java/com/toanyone/hub/application/service/HubServiceImpl.java
  hub/src/main/java/com/toanyone/hub/common/config/feignConfig/FeignConfig.java
  hub/src/main/java/com/toanyone/hub/common/config/feignConfig/NoHeaderFeignConfig.java
  hub/src/main/java/com/toanyone/hub/common/config/interceptor/UserInfoHeaderInterceptor.java
  hub/src/main/java/com/toanyone/hub/domain/service/HubService.java
  hub/src/main/java/com/toanyone/hub/infrastructure/client/SlackClient.java
  hub/src/main/java/com/toanyone/hub/infrastructure/messaging/KafkaConsumerService.java
  hub/src/main/java/com/toanyone/hub/presentation/controller/HubController.java
  item/src/main/java/com/toanyone/item/infrastructure/client/StoreClient.java
Labels: 🔧 fix

#87 배송 삭제 시 배송경로가 같이 삭제되지 않는 현상 수정
  delivery/src/main/java/com/toanyone/delivery/application/DeliveryService.java
  delivery/src/main/java/com/toanyone/delivery/application/dtos/request/DeliveryCompletedMessage.java
  delivery/src/main/java/com/toanyone/delivery/domain/Delivery.java
  delivery/src/main/java/com/toanyone/delivery/domain/DeliveryRoad.java
Labels: 🔧 fix
